#server:
#  port: 8081
spring:
  main:
    web-application-type: none

dubbo:
  application:
    name: connect-server #连接服务
  protocol:
    name: dubbo #dubbo协议
    port: -1 #dubbo端口 -1代表随机分配端口
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181 #zookeeper地址及端口号
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181


redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
  database: 0
  # redis服务器地址（默认为localhost）
  host: localhost
  # redis端口（默认为6379）
  port: 6379
  # redis访问密码（默认为空）
  password:
  # redis连接超时时间（单位毫秒）
  timeout: 0
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
