server:
  port: 8090

dubbo:
  application:
    name: bussiness-server #业务服务
  protocol:
    name: dubbo #dubbo协议
    port: -1 #dubbo端口 -1代表随机分配端口
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181 #zookeeper地址及端口号
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181